export const SET_ORDERBOOK_LOADED = 'SET_ORDERBOOK_LOADED'
export const SET_ORDERS_LIST = 'SET_ORDERS_LIST'
export const ADD_ORDERS_LIST = 'ADD_ORDERS_LIST'
export const RESET_HIGHLIGHTING = 'RESET_HIGHLIGHTING'
