import * as types from './types'

export const mergeTokens = payload => ({ type: types.MERGE_TOKENS, payload })
export const setAccount = payload => ({ type: types.SET_ACCOUNT, payload })
export const setApplicationNetwork = payload => ({ type: types.SET_APPLICATION_NETWORK, payload })
export const setClientNetwork = payload => ({ type: types.SET_CLIENT_NETWORK, payload })
export const setTokenBalance = (symbol, value) => ({ type: types.SET_TOKEN_BALANCE, payload: { symbol, value } })
export const setEthBalance = payload => ({ type: types.SET_ETH_BALANCE, payload })
export const setTokenAllowance = (symbol, value) => ({ type: types.SET_TOKEN_ALLOWANCE, payload: { symbol, value } })
export const setEnabled = payload => ({ type: types.SET_ENABLED, payload })
export const mergeMarkets = payload => ({ type: types.MERGE_MARKETS, payload })
export const addMarket = payload => ({ type: types.ADD_MARKET, payload })
export const setMarketCandles = payload => ({ type: types.SET_MARKET_CANDLES, payload })
export const setPriceChartInterval = payload => ({ type: types.SET_PRICE_CHART_INTERVAL, payload })
export const setMarketsLoaded = payload => ({ type: types.SET_MARKETS_LOADED, payload })
export const setMarketLoaded = payload => ({ type: types.SET_MARKET_LOADED, payload })
