export const ADD_TRADE_HISTORY_LIST = 'ADD_TRADE_HISTORY_LIST'
export const SET_TRADE_HISTORY_LIST = 'SET_TRADE_HISTORY_LIST'
export const SET_ASSET_PAIR_TRADE_HISTORY_LOADED = 'SET_ASSET_PAIR_TRADE_HISTORY_LOADED'
export const SET_ACCOUNT_TRADE_HISTORY_LOADED = 'SET_ACCOUNT_TRADE_HISTORY_LOADEDZ'
